### PR TITLE
New implementation of CORS detector #313

### PR DESCRIPTION
**Pull request by bradflood**
fix issue #313

### CODE REVIEW

**Comment by h3xstream** [comment]
@bradflood Please set your IDE to the default 4 spaces indentation. I know the motivation for 2 spaces (3 merge and stuff).

Can you do a rebase? This would help me review the actual changes.

**Comment by h3xstream** [comment]
I squash-merged your commits.

**Comment by bradflood** [comment]
thanks @h3xstream  I was hoping to get to this soon, but glad you could get past the formatting issues. I'll spend some time removing auto-formatting specifically for this project so as to avoid this in the future.

**Comment by h3xstream** [comment]
@bradflood Also reset your **local** `master` branch before doing your future changes. Otherwise, you'll have conflicts with your `master` that was rewritten. 😝

**Pull request merged**
