### PR TITLE
JstlExpressionWhiteLister now allows custom regular expressions

### PR DESCRIPTION
**Pull request by jbindel**
The JSTL expression white list for pattern XSS_JSP_PRINT has been hard-coded in JstlExpressionWhiteLister (In PR 451: https://github.com/find-sec-bugs/find-sec-bugs/pull/451). In order to avoid the XSS warnings on code that uses other libraries to sanitize expressions, this change allows additional regular expressions to be loaded from configuration files in a similar manner to loading custom taint configurations for Java code.

The system property "findsecbugs.jstlsafe.customregexfile" can point to a file containing additional safe regular expressions similar to the JstlExpressionWhiteLister.TAG_FOR_HTML_CONTENT_PATTERN regular expression.

For example, the file can contain an expression per line like this:

   ^\$\{\s*w:toSafeJSON\([a-zA-Z0-9\-#,\'\"\&\[\]@\\ \._\(\):]+\)\s*\}$
   ^\$\{\s*w:safeQuote\([a-zA-Z0-9\-#,\'\"\&\[\]@\\ \._\(\):]+\)\s*\}$

### CODE REVIEW

**Review by h3xstream — CHANGES_REQUESTED** [review]
The code looks good.
I would however put `toSafeJSON` and `safeQuote` in the default whitelist. 
https://github.com/find-sec-bugs/find-sec-bugs/pull/686/files#diff-eef9a5d401ec1549a6a48cb3341f5aeaef6ef39eae71e1ab727dfcd133d9c7bfR93-R95

**Comment by jbindel** [comment]
Commit 04cb2a80d2a911fbdddc20c0c936c17b3934f1f9 moves the "toSafeJSON" and "safeQuote" functions to the default whitelist and uses functions prefixed with "custom" for the custom safe methods.

**Review by h3xstream — APPROVED** [review]
Update looks good + great samples

**Comment by jbindel** [comment]
Great. Thank you for the feedback.

**Pull request merged**
