### PR TITLE
Update owasp.txt

### PR DESCRIPTION
**Pull request by s-tikhomirov**
Fix error: encodeFromURL --> decodeFromURL
https://owasp-esapi-java.googlecode.com/svn/trunk_doc/2.0-rc4/org/owasp/esapi/Encoder.html#decodeFromURL(java.lang.String)

### CODE REVIEW

**Comment by formanek** [comment]
Thanks

**Comment by h3xstream** [comment]
I'm not sure about the purpose of this modification.

[encodeForURL](https://owasp-esapi-java.googlecode.com/svn/trunk_doc/2.0-rc4/org/owasp/esapi/Encoder.html#encodeForURL(java.lang.String)) is expected to be safe from XSS in the specific context of URLs.

Example:
```java
String html = "<a href=\"http://"+Encoder.encodeFromURL(req.getParameter("input"))+"\">Click me</a>"
```

The decode on the other hand does not provide any protection regarding escaping..
```java
String html = "<a href=\"http://"+Encoder.decodeFromURL(req.getParameter("input"))+"\">Click me</a>"
```

**Comment by formanek** [comment]
@h3xstream the `-` sign before the tag means that tag is removed by the method, so the value is considered insecure after decoding even if it was encoded before.

**Comment by h3xstream** [comment]
@formanek Got it ! Thanks

**Pull request merged**
